/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRelatoriosRouteImport } from './routes/_app/relatorios'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppPedidosRouteImport } from './routes/_app/pedidos'
import { Route as AppMelhoriasRouteImport } from './routes/_app/melhorias'
import { Route as AppFluxosRouteImport } from './routes/_app/fluxos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCuponsRouteImport } from './routes/_app/cupons'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppAvaliacoesRouteImport } from './routes/_app/avaliacoes'
import { Route as AppAtendimentoRouteImport } from './routes/_app/atendimento'
import { Route as AppAnunciosRouteImport } from './routes/_app/anuncios'
import { Route as AppAgenteRouteImport } from './routes/_app/agente'
import { Route as AppAgendamentosRouteImport } from './routes/_app/agendamentos'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'
import { Route as ApiPublicTriggerAuditoriaRouteImport } from './routes/api/public/trigger-auditoria'
import { Route as ApiPublicRevisaoIaCronRouteImport } from './routes/api/public/revisao-ia-cron'
import { Route as ApiPublicPosVendaCronRouteImport } from './routes/api/public/pos-venda-cron'
import { Route as ApiPublicMetaAdsRouteImport } from './routes/api/public/meta-ads'
import { Route as ApiPublicFollowUpCronRouteImport } from './routes/api/public/follow-up-cron'
import { Route as ApiPublicEnviarMensagemRouteImport } from './routes/api/public/enviar-mensagem'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as AppIntegracoesNuvemshopRouteImport } from './routes/_app/integracoes/nuvemshop'
import { Route as AppFluxosIdRouteImport } from './routes/_app/fluxos_.$id'
import { Route as ApiPublicNuvemshopCallbackRouteImport } from './routes/api/public/nuvemshop/callback'
import { Route as ApiPublicHooksSyncNuvemshopProductsRouteImport } from './routes/api/public/hooks/sync-nuvemshop-products'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosRoute = AppPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AppRoute,
} as any)
const AppMelhoriasRoute = AppMelhoriasRouteImport.update({
  id: '/melhorias',
  path: '/melhorias',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxosRoute = AppFluxosRouteImport.update({
  id: '/fluxos',
  path: '/fluxos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCuponsRoute = AppCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAvaliacoesRoute = AppAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendimentoRoute = AppAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => AppRoute,
} as any)
const AppAnunciosRoute = AppAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenteRoute = AppAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendamentosRoute = AppAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTriggerAuditoriaRoute =
  ApiPublicTriggerAuditoriaRouteImport.update({
    id: '/api/public/trigger-auditoria',
    path: '/api/public/trigger-auditoria',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRevisaoIaCronRoute = ApiPublicRevisaoIaCronRouteImport.update({
  id: '/api/public/revisao-ia-cron',
  path: '/api/public/revisao-ia-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPosVendaCronRoute = ApiPublicPosVendaCronRouteImport.update({
  id: '/api/public/pos-venda-cron',
  path: '/api/public/pos-venda-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaAdsRoute = ApiPublicMetaAdsRouteImport.update({
  id: '/api/public/meta-ads',
  path: '/api/public/meta-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFollowUpCronRoute = ApiPublicFollowUpCronRouteImport.update({
  id: '/api/public/follow-up-cron',
  path: '/api/public/follow-up-cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnviarMensagemRoute = ApiPublicEnviarMensagemRouteImport.update({
  id: '/api/public/enviar-mensagem',
  path: '/api/public/enviar-mensagem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIntegracoesNuvemshopRoute = AppIntegracoesNuvemshopRouteImport.update({
  id: '/integracoes/nuvemshop',
  path: '/integracoes/nuvemshop',
  getParentRoute: () => AppRoute,
} as any)
const AppFluxosIdRoute = AppFluxosIdRouteImport.update({
  id: '/fluxos_/$id',
  path: '/fluxos/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicNuvemshopCallbackRoute =
  ApiPublicNuvemshopCallbackRouteImport.update({
    id: '/api/public/nuvemshop/callback',
    path: '/api/public/nuvemshop/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncNuvemshopProductsRoute =
  ApiPublicHooksSyncNuvemshopProductsRouteImport.update({
    id: '/api/public/hooks/sync-nuvemshop-products',
    path: '/api/public/hooks/sync-nuvemshop-products',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agendamentos': typeof AppAgendamentosRoute
  '/agente': typeof AppAgenteRoute
  '/anuncios': typeof AppAnunciosRoute
  '/atendimento': typeof AppAtendimentoRoute
  '/avaliacoes': typeof AppAvaliacoesRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/cupons': typeof AppCuponsRoute
  '/dashboard': typeof AppDashboardRoute
  '/fluxos': typeof AppFluxosRoute
  '/melhorias': typeof AppMelhoriasRoute
  '/pedidos': typeof AppPedidosRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/fluxos/$id': typeof AppFluxosIdRoute
  '/integracoes/nuvemshop': typeof AppIntegracoesNuvemshopRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/enviar-mensagem': typeof ApiPublicEnviarMensagemRoute
  '/api/public/follow-up-cron': typeof ApiPublicFollowUpCronRoute
  '/api/public/meta-ads': typeof ApiPublicMetaAdsRoute
  '/api/public/pos-venda-cron': typeof ApiPublicPosVendaCronRoute
  '/api/public/revisao-ia-cron': typeof ApiPublicRevisaoIaCronRoute
  '/api/public/trigger-auditoria': typeof ApiPublicTriggerAuditoriaRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/hooks/sync-nuvemshop-products': typeof ApiPublicHooksSyncNuvemshopProductsRoute
  '/api/public/nuvemshop/callback': typeof ApiPublicNuvemshopCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agendamentos': typeof AppAgendamentosRoute
  '/agente': typeof AppAgenteRoute
  '/anuncios': typeof AppAnunciosRoute
  '/atendimento': typeof AppAtendimentoRoute
  '/avaliacoes': typeof AppAvaliacoesRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/cupons': typeof AppCuponsRoute
  '/dashboard': typeof AppDashboardRoute
  '/fluxos': typeof AppFluxosRoute
  '/melhorias': typeof AppMelhoriasRoute
  '/pedidos': typeof AppPedidosRoute
  '/produtos': typeof AppProdutosRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/fluxos/$id': typeof AppFluxosIdRoute
  '/integracoes/nuvemshop': typeof AppIntegracoesNuvemshopRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/enviar-mensagem': typeof ApiPublicEnviarMensagemRoute
  '/api/public/follow-up-cron': typeof ApiPublicFollowUpCronRoute
  '/api/public/meta-ads': typeof ApiPublicMetaAdsRoute
  '/api/public/pos-venda-cron': typeof ApiPublicPosVendaCronRoute
  '/api/public/revisao-ia-cron': typeof ApiPublicRevisaoIaCronRoute
  '/api/public/trigger-auditoria': typeof ApiPublicTriggerAuditoriaRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/hooks/sync-nuvemshop-products': typeof ApiPublicHooksSyncNuvemshopProductsRoute
  '/api/public/nuvemshop/callback': typeof ApiPublicNuvemshopCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/agendamentos': typeof AppAgendamentosRoute
  '/_app/agente': typeof AppAgenteRoute
  '/_app/anuncios': typeof AppAnunciosRoute
  '/_app/atendimento': typeof AppAtendimentoRoute
  '/_app/avaliacoes': typeof AppAvaliacoesRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/cupons': typeof AppCuponsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/fluxos': typeof AppFluxosRoute
  '/_app/melhorias': typeof AppMelhoriasRoute
  '/_app/pedidos': typeof AppPedidosRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/fluxos_/$id': typeof AppFluxosIdRoute
  '/_app/integracoes/nuvemshop': typeof AppIntegracoesNuvemshopRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/enviar-mensagem': typeof ApiPublicEnviarMensagemRoute
  '/api/public/follow-up-cron': typeof ApiPublicFollowUpCronRoute
  '/api/public/meta-ads': typeof ApiPublicMetaAdsRoute
  '/api/public/pos-venda-cron': typeof ApiPublicPosVendaCronRoute
  '/api/public/revisao-ia-cron': typeof ApiPublicRevisaoIaCronRoute
  '/api/public/trigger-auditoria': typeof ApiPublicTriggerAuditoriaRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/public/hooks/sync-nuvemshop-products': typeof ApiPublicHooksSyncNuvemshopProductsRoute
  '/api/public/nuvemshop/callback': typeof ApiPublicNuvemshopCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agendamentos'
    | '/agente'
    | '/anuncios'
    | '/atendimento'
    | '/avaliacoes'
    | '/clientes'
    | '/configuracoes'
    | '/cupons'
    | '/dashboard'
    | '/fluxos'
    | '/melhorias'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/fluxos/$id'
    | '/integracoes/nuvemshop'
    | '/api/public/chat'
    | '/api/public/enviar-mensagem'
    | '/api/public/follow-up-cron'
    | '/api/public/meta-ads'
    | '/api/public/pos-venda-cron'
    | '/api/public/revisao-ia-cron'
    | '/api/public/trigger-auditoria'
    | '/api/public/whatsapp-webhook'
    | '/api/public/hooks/sync-nuvemshop-products'
    | '/api/public/nuvemshop/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agendamentos'
    | '/agente'
    | '/anuncios'
    | '/atendimento'
    | '/avaliacoes'
    | '/clientes'
    | '/configuracoes'
    | '/cupons'
    | '/dashboard'
    | '/fluxos'
    | '/melhorias'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/fluxos/$id'
    | '/integracoes/nuvemshop'
    | '/api/public/chat'
    | '/api/public/enviar-mensagem'
    | '/api/public/follow-up-cron'
    | '/api/public/meta-ads'
    | '/api/public/pos-venda-cron'
    | '/api/public/revisao-ia-cron'
    | '/api/public/trigger-auditoria'
    | '/api/public/whatsapp-webhook'
    | '/api/public/hooks/sync-nuvemshop-products'
    | '/api/public/nuvemshop/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/agendamentos'
    | '/_app/agente'
    | '/_app/anuncios'
    | '/_app/atendimento'
    | '/_app/avaliacoes'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/cupons'
    | '/_app/dashboard'
    | '/_app/fluxos'
    | '/_app/melhorias'
    | '/_app/pedidos'
    | '/_app/produtos'
    | '/_app/relatorios'
    | '/_app/fluxos_/$id'
    | '/_app/integracoes/nuvemshop'
    | '/api/public/chat'
    | '/api/public/enviar-mensagem'
    | '/api/public/follow-up-cron'
    | '/api/public/meta-ads'
    | '/api/public/pos-venda-cron'
    | '/api/public/revisao-ia-cron'
    | '/api/public/trigger-auditoria'
    | '/api/public/whatsapp-webhook'
    | '/api/public/hooks/sync-nuvemshop-products'
    | '/api/public/nuvemshop/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicEnviarMensagemRoute: typeof ApiPublicEnviarMensagemRoute
  ApiPublicFollowUpCronRoute: typeof ApiPublicFollowUpCronRoute
  ApiPublicMetaAdsRoute: typeof ApiPublicMetaAdsRoute
  ApiPublicPosVendaCronRoute: typeof ApiPublicPosVendaCronRoute
  ApiPublicRevisaoIaCronRoute: typeof ApiPublicRevisaoIaCronRoute
  ApiPublicTriggerAuditoriaRoute: typeof ApiPublicTriggerAuditoriaRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiPublicHooksSyncNuvemshopProductsRoute: typeof ApiPublicHooksSyncNuvemshopProductsRoute
  ApiPublicNuvemshopCallbackRoute: typeof ApiPublicNuvemshopCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos': {
      id: '/_app/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AppPedidosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/melhorias': {
      id: '/_app/melhorias'
      path: '/melhorias'
      fullPath: '/melhorias'
      preLoaderRoute: typeof AppMelhoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxos': {
      id: '/_app/fluxos'
      path: '/fluxos'
      fullPath: '/fluxos'
      preLoaderRoute: typeof AppFluxosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cupons': {
      id: '/_app/cupons'
      path: '/cupons'
      fullPath: '/cupons'
      preLoaderRoute: typeof AppCuponsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avaliacoes': {
      id: '/_app/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AppAvaliacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atendimento': {
      id: '/_app/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AppAtendimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/anuncios': {
      id: '/_app/anuncios'
      path: '/anuncios'
      fullPath: '/anuncios'
      preLoaderRoute: typeof AppAnunciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agente': {
      id: '/_app/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AppAgenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agendamentos': {
      id: '/_app/agendamentos'
      path: '/agendamentos'
      fullPath: '/agendamentos'
      preLoaderRoute: typeof AppAgendamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trigger-auditoria': {
      id: '/api/public/trigger-auditoria'
      path: '/api/public/trigger-auditoria'
      fullPath: '/api/public/trigger-auditoria'
      preLoaderRoute: typeof ApiPublicTriggerAuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/revisao-ia-cron': {
      id: '/api/public/revisao-ia-cron'
      path: '/api/public/revisao-ia-cron'
      fullPath: '/api/public/revisao-ia-cron'
      preLoaderRoute: typeof ApiPublicRevisaoIaCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pos-venda-cron': {
      id: '/api/public/pos-venda-cron'
      path: '/api/public/pos-venda-cron'
      fullPath: '/api/public/pos-venda-cron'
      preLoaderRoute: typeof ApiPublicPosVendaCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-ads': {
      id: '/api/public/meta-ads'
      path: '/api/public/meta-ads'
      fullPath: '/api/public/meta-ads'
      preLoaderRoute: typeof ApiPublicMetaAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/follow-up-cron': {
      id: '/api/public/follow-up-cron'
      path: '/api/public/follow-up-cron'
      fullPath: '/api/public/follow-up-cron'
      preLoaderRoute: typeof ApiPublicFollowUpCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/enviar-mensagem': {
      id: '/api/public/enviar-mensagem'
      path: '/api/public/enviar-mensagem'
      fullPath: '/api/public/enviar-mensagem'
      preLoaderRoute: typeof ApiPublicEnviarMensagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/integracoes/nuvemshop': {
      id: '/_app/integracoes/nuvemshop'
      path: '/integracoes/nuvemshop'
      fullPath: '/integracoes/nuvemshop'
      preLoaderRoute: typeof AppIntegracoesNuvemshopRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fluxos_/$id': {
      id: '/_app/fluxos_/$id'
      path: '/fluxos/$id'
      fullPath: '/fluxos/$id'
      preLoaderRoute: typeof AppFluxosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/nuvemshop/callback': {
      id: '/api/public/nuvemshop/callback'
      path: '/api/public/nuvemshop/callback'
      fullPath: '/api/public/nuvemshop/callback'
      preLoaderRoute: typeof ApiPublicNuvemshopCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-nuvemshop-products': {
      id: '/api/public/hooks/sync-nuvemshop-products'
      path: '/api/public/hooks/sync-nuvemshop-products'
      fullPath: '/api/public/hooks/sync-nuvemshop-products'
      preLoaderRoute: typeof ApiPublicHooksSyncNuvemshopProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAgendamentosRoute: typeof AppAgendamentosRoute
  AppAgenteRoute: typeof AppAgenteRoute
  AppAnunciosRoute: typeof AppAnunciosRoute
  AppAtendimentoRoute: typeof AppAtendimentoRoute
  AppAvaliacoesRoute: typeof AppAvaliacoesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCuponsRoute: typeof AppCuponsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFluxosRoute: typeof AppFluxosRoute
  AppMelhoriasRoute: typeof AppMelhoriasRoute
  AppPedidosRoute: typeof AppPedidosRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppFluxosIdRoute: typeof AppFluxosIdRoute
  AppIntegracoesNuvemshopRoute: typeof AppIntegracoesNuvemshopRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendamentosRoute: AppAgendamentosRoute,
  AppAgenteRoute: AppAgenteRoute,
  AppAnunciosRoute: AppAnunciosRoute,
  AppAtendimentoRoute: AppAtendimentoRoute,
  AppAvaliacoesRoute: AppAvaliacoesRoute,
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCuponsRoute: AppCuponsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFluxosRoute: AppFluxosRoute,
  AppMelhoriasRoute: AppMelhoriasRoute,
  AppPedidosRoute: AppPedidosRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppFluxosIdRoute: AppFluxosIdRoute,
  AppIntegracoesNuvemshopRoute: AppIntegracoesNuvemshopRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicEnviarMensagemRoute: ApiPublicEnviarMensagemRoute,
  ApiPublicFollowUpCronRoute: ApiPublicFollowUpCronRoute,
  ApiPublicMetaAdsRoute: ApiPublicMetaAdsRoute,
  ApiPublicPosVendaCronRoute: ApiPublicPosVendaCronRoute,
  ApiPublicRevisaoIaCronRoute: ApiPublicRevisaoIaCronRoute,
  ApiPublicTriggerAuditoriaRoute: ApiPublicTriggerAuditoriaRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiPublicHooksSyncNuvemshopProductsRoute:
    ApiPublicHooksSyncNuvemshopProductsRoute,
  ApiPublicNuvemshopCallbackRoute: ApiPublicNuvemshopCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
